"""empty message

Revision ID: 744329c51d15
Revises: 71adcb93bdde
Create Date: 2024-09-14 00:56:39.484995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744329c51d15'
down_revision = '71adcb93bdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
